### ISSUE TITLE
xades4j.verification.ReferenceValueException: no se puede validar la referencia

### ISSUE THREAD

**Issue by IngDanielleon** [miguelhuertas/efacturacion-colombia-firma#1]
Amigo al enviar mi documento electrónico a la DIAN me aparece este error tu me podrías especificar a que se debe y orientarme de como calculo los valores de la firma, me encuentro construyendo una libreria en php para el framework laravel, quiero subirla libre a un repositorio cuando ya este funcional.

**Comment by miguelhuertas** [comment]
@IngDanielleon te comento que hasta el momento no he realizado la implementación en PHP; según sé si es posible, quizá luego lo intente. De todos modos, si quieres puedes crear un repositorio (de desarrollo) y luego le doy un vistazo para ver que en que puedo aportar.

PD: Cerraré este hilo porque no tiene que ver con este repositorio directamente.

**Comment by IngDanielleon** [comment]
Lo que te pregunto no es como crear un repositorio, lo que te pregunto es si conoces el error presente.

**Comment by miguelhuertas** [comment]
Pues me aparecerieron varios (no recuerdo si ese) de ese tipo cuando estaba tratando de validar la firma pero no entendí exactamente a lo que se referían (excepto lo del issuername y otros).

Lo del repositorio te lo digo para revisar cómo lo estás haciendo y compararlo con el código C#.

**Comment by IngDanielleon** [comment]
tu de casualidad podrias subir a este repositorio una factura firmada de prueba, como puedo ejecutar este codigo?

**Comment by miguelhuertas** [comment]
https://www.dian.gov.co/fizcalizacioncontrol/herramienconsulta/FacturaElectronica/InformacionTecnica/Paginas/ejemplificacionesXML.aspx

**Comment by IngDanielleon** [comment]
https://facturaelectronica.dian.gov.co/politicadefirma/v2/politicadefirmav2.pdf
