### ISSUE TITLE
Implementación en otros lenguajes

### ISSUE THREAD

**Issue by saarboledazia** [miguelhuertas/efacturacion-colombia-firma#10]
Buenas tardes, escribo para saber si es posible que se haga una guía para implementar el código en otros lenguajes e.g PHP.

Yo por mi parte llevo una parte del proceso ya hecha, precisamente tengo una duda en lo que respecta al valor del DigestValue de la Referencia 1, no sé a qué valor corresponde realmente, según lo entendido se debe hacer hash del documento, pero en este caso no sé si se refiere a todo el documento XML de facturación electrónica sin la firma, o al elemento <Signature> sin el <SignedInfo>, si me pudieras resolver esa pequeña duda sería de grandísima ayuda.

**Comment by miguelhuertas** [comment]
Hola @saarboledazia, este repositorio ya ha quedado obsoleto.
Respecto al DigestValue, es del documento XML sin la firma.
Saludos
