### ISSUE TITLE
Error Firma Invalida

### ISSUE THREAD

**Issue by DGoRdriguez** [miguelhuertas/efacturacion-colombia-firma#6]
Miguel, antes que nada tu aporte es excelente. 
Quisiera saber si me podrias ayudar con el siguiente error que me da la DIAN al enviar el XML.

com.indra.mmdd.signature.exceptions.ValidateException: xades4j.providers.CannotSelectCertificateException: The available certificate selector didn't match any certificates

**Comment by miguelhuertas** [comment]
Hola @DGoRdriguez 
Quién es el proveedor de tu certificado digital?

**Comment by DGoRdriguez** [comment]
Hola @miguelhuertas  Es Certicámara.

**Comment by miguelhuertas** [comment]
@DGoRdriguez puedes colocar el código que usas para firmar?

**Comment by DGoRdriguez** [comment]
@miguelhuertas Tome código compartido como base y realice las modificaciones sobre la clase FirmaXades.XadesService te comparto la modificación,es una modificación en el método AddSignatureProperties para generar la cadena de certificación del Certificado en la firma.

[XadesService.cs.docx](https://github.com/miguelhuertas/efacturacion-colombia-firma/files/2765223/XadesService.cs.docx)

**Comment by miguelhuertas** [comment]
@DGoRdriguez Gracias, voy a revisar el código. ¿Con esto solucionaste tu problema?

**Comment by DGoRdriguez** [comment]
@miguelhuertas No he encontrado la solución sigue indicando el validador que hay un error en la Firma.


<ns3:PropiedadesTecnicas>
                     <ns3:PropiedadVeriTec>java.exception.msg</ns3:PropiedadVeriTec>
                     <ns3:DescripcionVeriTec>com.indra.mmdd.signature.exceptions.ValidateException: xades4j.providers.CannotSelectCertificateException: The available certificate selector didn't match any certificates</ns3:DescripcionVeriTec>
                  </ns3:PropiedadesTecnicas>

**Comment by miguelhuertas** [comment]
@DGoRdriguez Y usando el código original te pasa lo mismo?

**Comment by DGoRdriguez** [comment]
Nos da otro error Dado que no se escribe la cadena de certificación del certificado.

**Comment by DGoRdriguez** [comment]
Adicional el el KyInfo fue necesario agregar el subject y serialnumber del cerrificado

**Comment by DGoRdriguez** [comment]
Miguel Muchas Gracias, te compartí el email.
